use alloc::boxed::Box;
use core::any::{Any, TypeId};

use crate::info::{DynamicTypePath, TypePath};

/// A abstract trait representing the capabilities supported by a type.
///
/// `TypeTrait` can be registered to the [`TypeRegistry`] and stored on a type's [`TypeMeta`](crate::registry::TypeMeta).
///
/// Almost any type that implements [`Clone`] and [`TypePath`] can be considered "type trait".
/// This is because it has a blanket implementation over all `T` where `T: TypePath + Clone + Send + Sync + 'static`.
///
/// While custom type trait is often generated using the [`#[reflect_trait]`](crate::derive::reflect_trait) macro.
///
/// # Naming Convention
///
/// We provided some `TypeTrait`s with `Reflect` prefix, such as:
/// - [`ReflectDefault`](crate::registry::ReflectDefault)
/// - [`ReflectFromPtr`](crate::registry::ReflectFromPtr)
/// - [`ReflectFromReflect`](crate::registry::ReflectFromReflect)
/// - [`ReflectSerialize`](crate::registry::ReflectSerialize)
/// - [`ReflectDeserialize`](crate::registry::ReflectDeserialize)
///
/// They provide some methods similar to the original trait, but the param type changed to reflection type.
///
/// The trait generated by [`reflect_trait`] is suffixed with `FromReflect`, instead of prefix `Reflect`,
/// because it provides three conversion methods: `from_ref`, `from_mut`, and `from_boxed`.
/// See [`reflect_trait` macro attribute](crate::derive::reflect_trait) for more details.
///
/// # Implementation
///
/// ## Use [`#[reflect_trait]`](crate::derive::reflect_trait) macro
///
/// ```
/// use vc_reflect::{derive::reflect_trait, registry::FromType};
///
/// #[reflect_trait]
/// trait MyDisplay {
///     fn display(&self) { /* ... */ }
/// }
///
/// impl MyDisplay for i32{}
///
/// let reflect_trait = <MyDisplayFromReflect as FromType<i32>>::from_type();
/// ```
///
/// ## Manually
///
/// ```
/// use vc_reflect::{derive::TypePath, registry::TypeTrait};
///
/// #[derive(Clone, TypePath)]
/// struct K{ /* ... */ }
///
/// let k = K{ /* ... */ };
/// let type_trait: &dyn TypeTrait = &k;
/// ```
///
/// See the [crate-level documentation] for more information on type_trait and type_meta.
///
/// [`reflect_trait`]: crate::derive::reflect_trait
/// [`TypePath`]: crate::info::TypePath
/// [`TypeRegistry`]: crate::registry::TypeRegistry
/// [crate-level documentation]: crate
pub trait TypeTrait: DynamicTypePath + Any + Send + Sync {
    fn clone_type_trait(&self) -> Box<dyn TypeTrait>;
}

impl<T: Clone + TypePath + Any + Send + Sync> TypeTrait for T {
    #[inline]
    fn clone_type_trait(&self) -> Box<dyn TypeTrait> {
        Box::new(self.clone())
    }
}

impl dyn TypeTrait {
    /// Returns `true` if the underlying value is of type `T`.
    ///
    /// Note that this is a comparison of its own type,
    /// not the target type that implemented this trait.
    #[inline(always)]
    pub fn is<T: Any>(&self) -> bool {
        self.type_id() == TypeId::of::<T>()
    }

    /// Downcasts the value to type `T` by reference.
    #[inline(always)]
    pub fn downcast_ref<T: Any>(&self) -> Option<&T> {
        <dyn Any>::downcast_ref(self)
    }

    /// Downcasts the value to type `T` by mutable reference.
    #[inline(always)]
    pub fn downcast_mut<T: Any>(&mut self) -> Option<&mut T> {
        <dyn Any>::downcast_mut(self)
    }
}

impl core::fmt::Debug for dyn TypeTrait {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(DynamicTypePath::reflect_type_name(self))
    }
}

// -----------------------------------------------------------------------------
// tests

#[cfg(test)]
mod tests {
    use super::TypeTrait;
    use crate::derive::TypePath;

    #[derive(Clone, TypePath)]
    struct Marker(bool);

    #[test]
    fn clone_debug_and_downcast() {
        let marker = Marker(true);
        let type_trait: &dyn TypeTrait = &marker;

        assert!(type_trait.is::<Marker>());
        assert_eq!(type_trait.downcast_ref::<Marker>().unwrap().0, true);
        assert_eq!(alloc::format!("{type_trait:?}"), "Marker");

        let cloned = type_trait.clone_type_trait();
        assert_eq!(cloned.downcast_ref::<Marker>().unwrap().0, true);
    }
}
